# Generated by Django 6.0.3 on 2026-03-09 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(blank=True, help_text='An optional image displayed alongside the question.', null=True, upload_to='question_images/', verbose_name='Figure')),
                ('content', models.TextField(help_text='Enter the question text.', verbose_name='Question')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after the question is answered.', verbose_name='Explanation')),
                ('answer_order', models.CharField(choices=[('content', 'Content'), ('random', 'Random'), ('none', 'None')], default='random', help_text='The order in which answers are displayed.', max_length=30)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
                'verbose_name_plural': 'Multiple Choice Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='Answer')),
                ('correct', models.BooleanField(default=False, help_text='Is this the correct answer?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.mcquestion')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField(blank=True, default='', verbose_name='Score')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='A description of the quiz.')),
                ('url', models.SlugField(help_text='A user-friendly URL slug.', max_length=60, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, help_text='An optional image for the quiz.', null=True, upload_to='quiz_images/')),
                ('random_order', models.BooleanField(default=False, help_text='Display the questions in a random order each time?', verbose_name='Random Order')),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='Number of questions to show (random subset). Leave blank to show all.', null=True, verbose_name='Max Questions')),
                ('answers_at_end', models.BooleanField(default=False, help_text='Show correct answers only after quiz completion?', verbose_name='Answers at End')),
                ('exam_paper', models.BooleanField(default=False, help_text='If yes, the result of each attempt is stored. Necessary for marking.', verbose_name='Exam Paper')),
                ('single_attempt', models.BooleanField(default=False, help_text='If yes, only one attempt per user is allowed.', verbose_name='Single Attempt')),
                ('pass_mark', models.SmallIntegerField(default=0, help_text='Percentage required to pass. 0 means no pass mark.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark (%)')),
                ('success_text', models.TextField(blank=True, help_text='Displayed if the user passes.', verbose_name='Success Text')),
                ('fail_text', models.TextField(blank=True, help_text='Displayed if the user fails.', verbose_name='Fail Text')),
                ('draft', models.BooleanField(default=False, help_text='If yes, the quiz is not publicly visible.', verbose_name='Draft')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.category')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['title'],
                'permissions': (('view_sittings', 'Can see completed exams.'),),
            },
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='mc_questions', to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.TextField(help_text='JSON list of question PKs in display order.', verbose_name='Question Order')),
                ('question_list', models.TextField(help_text='JSON list of dicts with pk and type.', verbose_name='Question List')),
                ('incorrect_questions', models.TextField(blank=True, help_text='Comma-separated PKs of incorrect answers.', verbose_name='Incorrect Questions')),
                ('current_score', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('user_answers', models.TextField(default='{}', help_text='JSON dict mapping question pk to user answer.', verbose_name='User Answers')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to='quiz.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sittings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sitting',
                'verbose_name_plural': 'Sittings',
                'ordering': ['-start'],
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='quiz.category')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mcquestion',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subcategory'),
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(blank=True, help_text='An optional image displayed alongside the question.', null=True, upload_to='question_images/', verbose_name='Figure')),
                ('content', models.TextField(help_text='Enter the question text.', verbose_name='Question')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after the question is answered.', verbose_name='Explanation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
                ('quiz', models.ManyToManyField(blank=True, related_name='essay_questions', to='quiz.quiz')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subcategory')),
            ],
            options={
                'verbose_name': 'Essay Question',
                'verbose_name_plural': 'Essay Questions',
            },
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(blank=True, help_text='An optional image displayed alongside the question.', null=True, upload_to='question_images/', verbose_name='Figure')),
                ('content', models.TextField(help_text='Enter the question text.', verbose_name='Question')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after the question is answered.', verbose_name='Explanation')),
                ('correct', models.BooleanField(default=False, help_text='Tick if the correct answer is True.', verbose_name='Correct Answer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.category')),
                ('quiz', models.ManyToManyField(blank=True, related_name='tf_questions', to='quiz.quiz')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subcategory')),
            ],
            options={
                'verbose_name': 'True/False Question',
                'verbose_name_plural': 'True/False Questions',
            },
        ),
    ]
