# Generated by Django 6.0.3 on 2026-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for the quiz in minutes. Leave blank for no limit.', null=True, verbose_name='Time Limit (minutes)'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='graded_essays',
            field=models.TextField(blank=True, help_text='Comma-separated PKs of already marked essay questions.', verbose_name='Graded Essays'),
        ),
    ]
