# Generated by Django 6.0.3 on 2026-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_hide_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='featured',
            field=models.BooleanField(default=False, help_text='If yes, this quiz will be the ONLY one visible to students.', verbose_name='Featured'),
        ),
    ]
